[build]
  framework = "next"
  publish = ".next"
  command = "npm run build"
  edge_functions = "netlify/edge-functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
 path = "/*"
 function = "cache-page"
